# <font color='Blue'>Data Science Academy - Python Fundamentos - Capítulo 8</font>

## Pandas

Para poder trabalhar com Pandas, você deve conhecer bem estas duas estruturas: Series e DataFrama.

Para importar o pandas, utilize: import pandas as pd

Você também pode utilizar: from pandas import Series, DataFrame

Para atualizar o Pandas, abra o prompt de comando ou terminal e digite: pip install pandas -U

## Series

Series é um array unidimensional que contém um array de dados e um array de labels, chamando índice.

In [1]:
from pandas import Series

In [2]:
import pandas as pd

In [3]:
pd.__version__

'1.4.1'

In [4]:
# Criando uma série sem especificar os índices
Obj = Series([67, 78, -56, 13])

In [5]:
Obj

0    67
1    78
2   -56
3    13
dtype: int64

In [6]:
type(Obj)

pandas.core.series.Series

In [7]:
Obj.values

array([ 67,  78, -56,  13], dtype=int64)

In [8]:
Obj.index

RangeIndex(start=0, stop=4, step=1)

In [9]:
# Criando uma série e especificando os índices
Obj2 = Series([67, 78, -56, 13], index = ['a', 'b', 'c', 'd'])

In [10]:
Obj2

a    67
b    78
c   -56
d    13
dtype: int64

In [11]:
Obj.values

array([ 67,  78, -56,  13], dtype=int64)

In [12]:
Obj2.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [13]:
Obj2[Obj2 > 3]

a    67
b    78
d    13
dtype: int64

In [14]:
Obj2['d']

13

In [15]:
'd' in Obj2

True

In [16]:
# Criando uma série de dados passando um dicionário como parâmetro
dict = {'Futebol': 5200, 'Tenis': 120, 'Natação': 698, 'Volleyball': 1550}

In [17]:
# Criando uma série a partir de um dicionário
Obj3 = Series(dict)

In [18]:
Obj3

Futebol       5200
Tenis          120
Natação        698
Volleyball    1550
dtype: int64

In [19]:
type(Obj3)

pandas.core.series.Series

In [20]:
# Criando uma lista
esportes = ['Futebol', 'Tenis', 'Natação', 'Baskteball']

In [21]:
# Criando uma série e usando uma lista como índice
Obj4 = Series(dict, index = esportes)

In [22]:
Obj4

Futebol       5200.0
Tenis          120.0
Natação        698.0
Baskteball       NaN
dtype: float64

In [23]:
pd.isnull(Obj4)

Futebol       False
Tenis         False
Natação       False
Baskteball     True
dtype: bool

In [24]:
pd.notnull(Obj4)

Futebol        True
Tenis          True
Natação        True
Baskteball    False
dtype: bool

In [25]:
Obj4.isnull()

Futebol       False
Tenis         False
Natação       False
Baskteball     True
dtype: bool

In [26]:
# Concatenando Séries
Obj3 + Obj4

Baskteball        NaN
Futebol       10400.0
Natação        1396.0
Tenis           240.0
Volleyball        NaN
dtype: float64

In [27]:
Obj4.name = 'população'

In [28]:
Obj4.index.name = 'esporte'

In [29]:
Obj4

esporte
Futebol       5200.0
Tenis          120.0
Natação        698.0
Baskteball       NaN
Name: população, dtype: float64

## Dataframes

Dataframes representam uma estrutura tabular semelhante a estrutura de uma planilha do Excel, contendo uma coleção de colunas em que cada uma pode ser um diferente tipo de valor (número, string, etc...). Os Dataframes possuem index e linhas e esta estrutura é muito semelhante a um dataframe em R. Os dados de um dataframe são armazenados e um ou mais blocos bidimensionais, ao ínves de listas, dicionários ou alguma outra estrutura de array.

In [30]:
from pandas import DataFrame

In [31]:
data = {'Estado': ['Santa Catarina', 'Paraná', 'Goiás', 'Bahia', 'Minas Gerais'],
        'Ano': [2002, 2003, 2004, 2005, 2006],
        'População': [1.5, 1.7, 3.6, 2.4, 2.9]}

In [32]:
frame = DataFrame(data)

In [33]:
frame

Estado   Ano  População
0  Santa Catarina  2002        1.5
1          Paraná  2003        1.7
2           Goiás  2004        3.6
3           Bahia  2005        2.4
4    Minas Gerais  2006        2.9

In [34]:
type(frame)

pandas.core.frame.DataFrame

In [35]:
DataFrame(data, columns = ['Ano', 'Estado', 'População'])

Ano          Estado  População
0  2002  Santa Catarina        1.5
1  2003          Paraná        1.7
2  2004           Goiás        3.6
3  2005           Bahia        2.4
4  2006    Minas Gerais        2.9

In [36]:
# Criando outro dataframe com os mesmo dados anteriores mas adicionando uma coluna
frame2 = DataFrame(data, columns = ['Ano', 'Estado', 'População', 'Débito'],
                   index = ['um', 'dois', 'três', 'quatro', 'cinco'])

In [37]:
# Imprimindo o Dataframe
frame2

Ano          Estado  População Débito
um      2002  Santa Catarina        1.5    NaN
dois    2003          Paraná        1.7    NaN
três    2004           Goiás        3.6    NaN
quatro  2005           Bahia        2.4    NaN
cinco   2006    Minas Gerais        2.9    NaN

In [38]:
# Imprimindo apenas uma coluna do Dataframe
frame2['Estado']

um        Santa Catarina
dois              Paraná
três               Goiás
quatro             Bahia
cinco       Minas Gerais
Name: Estado, dtype: object

In [39]:
type(frame2)

pandas.core.frame.DataFrame

In [40]:
frame2.index

Index(['um', 'dois', 'três', 'quatro', 'cinco'], dtype='object')

In [41]:
frame2.columns

Index(['Ano', 'Estado', 'População', 'Débito'], dtype='object')

In [42]:
frame2.values

array([[2002, 'Santa Catarina', 1.5, nan],
       [2003, 'Paraná', 1.7, nan],
       [2004, 'Goiás', 3.6, nan],
       [2005, 'Bahia', 2.4, nan],
       [2006, 'Minas Gerais', 2.9, nan]], dtype=object)

In [43]:
frame2.dtypes

Ano            int64
Estado        object
População    float64
Débito        object
dtype: object

In [44]:
frame2['Ano']

um        2002
dois      2003
três      2004
quatro    2005
cinco     2006
Name: Ano, dtype: int64

In [45]:
frame2.Ano

um        2002
dois      2003
três      2004
quatro    2005
cinco     2006
Name: Ano, dtype: int64

In [46]:
frame2[:2]

Ano          Estado  População Débito
um    2002  Santa Catarina        1.5    NaN
dois  2003          Paraná        1.7    NaN

## Usando NumPy e Pandas

In [47]:
# Importando o NumPy
import numpy as np

In [48]:
# Usando o NumPy para alimentar uma das colunas do dataframe
frame2['Débito'] = np.arange(5.)

In [49]:
frame2

Ano          Estado  População  Débito
um      2002  Santa Catarina        1.5     0.0
dois    2003          Paraná        1.7     1.0
três    2004           Goiás        3.6     2.0
quatro  2005           Bahia        2.4     3.0
cinco   2006    Minas Gerais        2.9     4.0

In [50]:
frame2.values

array([[2002, 'Santa Catarina', 1.5, 0.0],
       [2003, 'Paraná', 1.7, 1.0],
       [2004, 'Goiás', 3.6, 2.0],
       [2005, 'Bahia', 2.4, 3.0],
       [2006, 'Minas Gerais', 2.9, 4.0]], dtype=object)

In [51]:
# Resumo do Dataframe
frame2.describe()

Ano  População    Débito
count     5.000000   5.000000  5.000000
mean   2004.000000   2.420000  2.000000
std       1.581139   0.864292  1.581139
min    2002.000000   1.500000  0.000000
25%    2003.000000   1.700000  1.000000
50%    2004.000000   2.400000  2.000000
75%    2005.000000   2.900000  3.000000
max    2006.000000   3.600000  4.000000

In [52]:
frame2['dois':'quatro']

Ano  Estado  População  Débito
dois    2003  Paraná        1.7     1.0
três    2004   Goiás        3.6     2.0
quatro  2005   Bahia        2.4     3.0

In [ ]:
frame2 < 5

## Localizando Registros Dentro do Dataframe

In [53]:
frame2.loc['quatro']

Ano           2005
Estado       Bahia
População      2.4
Débito         3.0
Name: quatro, dtype: object

In [54]:
frame2.iloc[2]

Ano           2004
Estado       Goiás
População      3.6
Débito         2.0
Name: três, dtype: object

## Invertendo as Colunas e Índices

In [55]:
# Criando um dicionário
web_status = {'Dias': [1, 2, 3, 4, 5, 6, 7],
              'Visitantes': [45, 23, 67, 78, 23, 12, 14],
              'Taxas': [11, 22, 33, 44, 55, 66, 77]}

In [56]:
df = pd.DataFrame(web_status)

In [57]:
print(df)

   Dias  Visitantes  Taxas
0     1          45     11
1     2          23     22
2     3          67     33
3     4          78     44
4     5          23     55
5     6          12     66
6     7          14     77


In [58]:
# Visualizando uma coluna index
print(df.set_index('Dias'))

      Visitantes  Taxas
Dias                   
1             45     11
2             23     22
3             67     33
4             78     44
5             23     55
6             12     66
7             14     77


In [59]:
print(df.head())

   Dias  Visitantes  Taxas
0     1          45     11
1     2          23     22
2     3          67     33
3     4          78     44
4     5          23     55


In [60]:
print(df['Visitantes'])

0    45
1    23
2    67
3    78
4    23
5    12
6    14
Name: Visitantes, dtype: int64


In [61]:
print(df[['Visitantes', 'Taxas']])

   Visitantes  Taxas
0          45     11
1          23     22
2          67     33
3          78     44
4          23     55
5          12     66
6          14     77


## Dataframes e Arquivos csv

In [62]:
# Usando o método read_csv
df = pd.read_csv('salarios.csv')

In [63]:
df

Name            Position Title        Department  \
0          AARON,  ELVIA J          WATER RATE TAKER       WATER MGMNT   
1        AARON,  JEFFERY M            POLICE OFFICER            POLICE   
2           AARON,  KARINA            POLICE OFFICER            POLICE   
3      AARON,  KIMBERLEI R  CHIEF CONTRACT EXPEDITER  GENERAL SERVICES   
4      ABAD JR,  VICENTE M         CIVIL ENGINEER IV       WATER MGMNT   
...                    ...                       ...               ...   
32177   ZYGOWICZ,  PETER J            POLICE OFFICER            POLICE   
32178    ZYMANTAS,  MARK E            POLICE OFFICER            POLICE   
32179  ZYRKOWSKI,  CARLO E            POLICE OFFICER            POLICE   
32180  ZYSKOWSKI,  DARIUSZ   CHIEF DATA BASE ANALYST              DoIT   
32181                  NaN                       NaN               NaN   

      Employee Annual Salary  
0                  $88965.00  
1                  $80778.00  
2                  $80778.00  
3                  $84780.00  
4                 $104736.00  
...                      ...  
32177              $86520.00  
32178              $83616.00  
32179              $86520.00  
32180             $110352.00  
32181                    NaN  

[32182 rows x 4 columns]