# <font color='Blue'>Data Science Academy - Python Fundamentos - Capítulo 8</font>

## NumPy

Para importar numpy, utilize: import numpy as np

Você também pode utilizar: from numpy import*. Isso evitará a utilização de np., mas este comando importará todos os modulos do NumPy.

Para atualizar o NumPy, abra o prompt de comando e digite: pip install numpy -U

In [1]:
# Importando o NumPy
import numpy as np

In [2]:
np.__version__

'1.22.2'

In [3]:
# Help
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', '

In [4]:
# Array criado a partir de uma lista:
vetor1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [5]:
print(vetor1)

[0 1 2 3 4 5 6 7 8]


In [6]:
# Um objeto do tipo ndarray é um recipiente multidimensionalde itens do mesmo tipo e tamanho.
type(vetor1)

numpy.ndarray

In [7]:
# Usando métodos do array NumPy - cumsum(Calcula a soma acumulada)
vetor1.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36])

In [8]:
# Criando uma lista. Perceba como listas e arrays são objetos diferentes, com diferentes propriedades
lst = [0, 1, 2, 3, 4, 5, 6, 7, 8]

In [9]:
lst

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [10]:
type(lst)

list

In [11]:
# Imprimindo na tela um elemento específico no array
vetor1[0]

0

In [12]:
# Alterando um elemento do array
vetor1[0] = 100

In [13]:
print(vetor1)

[100   1   2   3   4   5   6   7   8]


In [14]:
# Não é possível incluir elemento de outro tipo
vetor1[0] = 'Novo elemento'

ValueError: invalid literal for int() with base 10: 'Novo elemento'

In [ ]:
# Verificando o formato do array
print(vetor1.shape)

## Funções NumPy

In [15]:
# A função arrange cria um vetor contendo uma progressão aritmética a partir de um intervalo - start, stop, step
vetor2 = np.arange(0., 4.5, .5)

In [16]:
print(vetor2)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4. ]


In [17]:
# Verificando o tipo do objeto
type(vetor2)

numpy.ndarray

In [18]:
# Formato do array
np.shape(vetor2)

(9,)

In [19]:
print(vetor2.dtype)

float64


In [20]:
x = np.arange(1, 10, 0.25)
print(x)

[1.   1.25 1.5  1.75 2.   2.25 2.5  2.75 3.   3.25 3.5  3.75 4.   4.25
 4.5  4.75 5.   5.25 5.5  5.75 6.   6.25 6.5  6.75 7.   7.25 7.5  7.75
 8.   8.25 8.5  8.75 9.   9.25 9.5  9.75]


In [21]:
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [22]:
# Retorna 1 nas posições em diagonal e 0 no restante
z = np.eye(3)

In [23]:
z

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
# Os valores passados como parâmetro, formam uma diagonal
d = np.diag(np.array([1, 2, 3, 4]))

In [25]:
d

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [26]:
# Array de números complexos
c = np.array([1 + 2j, 3 + 4j, 5 + 6 * 1j])

In [27]:
c

array([1.+2.j, 3.+4.j, 5.+6.j])

In [28]:
# Array de valores booleanos
b = np.array([True, False, False, True])

In [29]:
b

array([ True, False, False,  True])

In [30]:
# Array de strings
s = np.array(['Python', 'R', 'Julia'])

In [31]:
s

array(['Python', 'R', 'Julia'], dtype='<U6')

In [32]:
# O método linspace (linearly spaced vector) retorna um número de valores igualmente distribuídos no intervalo especificado
np.linspace(0, 10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [33]:
print(np.linspace(0, 10, 15))

[ 0.          0.71428571  1.42857143  2.14285714  2.85714286  3.57142857
  4.28571429  5.          5.71428571  6.42857143  7.14285714  7.85714286
  8.57142857  9.28571429 10.        ]


In [34]:
print(np.logspace(0, 5, 10))

[1.00000000e+00 3.59381366e+00 1.29154967e+01 4.64158883e+01
 1.66810054e+02 5.99484250e+02 2.15443469e+03 7.74263683e+03
 2.78255940e+04 1.00000000e+05]


## Criando Matrizes

In [35]:
# Criando uma matriz
matriz = np.array([[1, 2, 3], [4, 5, 6]])

In [36]:
print(matriz)

[[1 2 3]
 [4 5 6]]


In [37]:
print(matriz.shape)

(2, 3)


In [38]:
# Criando uma matrix 2x3 apenas com números "1"
matriz1 = np.ones((2, 3))

In [39]:
print(matriz1)

[[1. 1. 1.]
 [1. 1. 1.]]


In [40]:
# Criando uma matriz a partir de uma lista de listas
lista = [[13, 81, 22], [0, 34, 59], [21, 48, 94]]

In [41]:
# A Função matriz cria uma matria a partir de uma sequência
matriz2 = np.matrix(lista)

In [42]:
matriz2

matrix([[13, 81, 22],
        [ 0, 34, 59],
        [21, 48, 94]])

In [43]:
type(matriz2)

numpy.matrix

In [44]:
# Formato da matriz
np.shape(matriz2)

(3, 3)

In [45]:
matriz2.size

9

In [46]:
print(matriz2.dtype)

int32


In [47]:
matriz2.itemsize

4

In [48]:
matriz2.nbytes

36

In [49]:
print(matriz2[2, 1])

48


In [50]:
# Alterando um elemento da matriz
matriz2[1, 0] = 100

In [51]:
matriz2

matrix([[ 13,  81,  22],
        [100,  34,  59],
        [ 21,  48,  94]])

In [52]:
x = np.array([1, 2])  # NumPy decide o tipo dos dados
y = np.array([1.0, 2.0])  # NumPy decide o tipo dos dados
z = np.array([1, 2], dtype = np.float64)  # Forçamos um tipo de dado em particular

print(x.dtype, y.dtype, z.dtype)

int32 float64 float64


In [53]:
matriz3 = np.array([[24, 76], [35, 89]], dtype = float)

In [54]:
matriz3

array([[24., 76.],
       [35., 89.]])

In [55]:
matriz3.itemsize

8

In [56]:
matriz3.nbytes

32

In [57]:
matriz3.ndim

2

In [58]:
matriz3[1, 1]

89.0

In [59]:
matriz3[1, 1] = 100

In [60]:
matriz3

array([[ 24.,  76.],
       [ 35., 100.]])

## Usando o Método random() do NumPy

In [61]:
print(np.random.rand(10))

[0.79881092 0.39740627 0.07065097 0.22267464 0.70602793 0.96738751
 0.08606272 0.55587005 0.71316789 0.8122448 ]


In [ ]:
import matplolib.pyplot as plt
%matplotlib inline

In [62]:
print(np.random.rand(10))

[0.02658187 0.03267074 0.55278021 0.08412554 0.24365401 0.46657567
 0.54007142 0.31065706 0.60527602 0.51674858]


In [ ]:
plt.show((plt.hist(np.random.rand(1000))))

In [63]:
print(np.random.randn(5, 5))

[[-0.61666021 -1.55285494 -0.06220863 -1.08215264 -0.42944774]
 [-0.29818619 -1.80078403  1.0469784   0.8940883  -0.02858387]
 [ 2.88985339  1.03276216 -1.55745751  0.5327509   2.06043652]
 [ 0.55521878  0.52914028  0.2155565  -1.6272492  -0.02364413]
 [ 0.68340761 -0.51809139  1.10638695 -0.74922524  0.44782731]]


In [ ]:
plt.show(plt.hist(np.random.randn(1000)))

In [ ]:
imagem = np.random.rand(30, 30)
plt.imshow(imagem, cmap = plt.cm.hot)
plt.colorbar()

## Operações com datasets

In [64]:
import os
filename = os.path.join('iris.csv')

In [65]:
# No Windows use !more iris.csv. Mac ou Linux use !head iris.csv
!more iris.csv

sepal_length,sepal_width,petal_length,petal_width,species
5.1,3.5,1.4,0.2,setosa
4.9,3,1.4,0.2,setosa
4.7,3.2,1.3,0.2,setosa
4.6,3.1,1.5,0.2,setosa
5,3.6,1.4,0.2,setosa
5.4,3.9,1.7,0.4,setosa
4.6,3.4,1.4,0.3,setosa
5,3.4,1.5,0.2,setosa
4.4,2.9,1.4,0.2,setosa
4.9,3.1,1.5,0.1,setosa
5.4,3.7,1.5,0.2,setosa
4.8,3.4,1.6,0.2,setosa
4.8,3,1.4,0.1,setosa
4.3,3,1.1,0.1,setosa
5.8,4,1.2,0.2,setosa
5.7,4.4,1.5,0.4,setosa
5.4,3.9,1.3,0.4,setosa
5.1,3.5,1.4,0.3,setosa
5.7,3.8,1.7,0.3,setosa
5.1,3.8,1.5,0.3,setosa
5.4,3.4,1.7,0.2,setosa
5.1,3.7,1.5,0.4,setosa
4.6,3.6,1,0.2,setosa
5.1,3.3,1.7,0.5,setosa
4.8,3.4,1.9,0.2,setosa
5,3,1.6,0.2,setosa
5,3.4,1.6,0.4,setosa
5.2,3.5,1.5,0.2,setosa
5.2,3.4,1.4,0.2,setosa
4.7,3.2,1.6,0.2,setosa
4.8,3.1,1.6,0.2,setosa
5.4,3.4,1.5,0.4,setosa
5.2,4.1,1.5,0.1,setosa
5.5,4.2,1.4,0.2,setosa
4.9,3.1,1.5,0.1,setosa
5,3.2,1.2,0.2,setosa
5.5,3.5,1.3,0.2,setosa
4.9,3.1,1.5,0.1,setosa
4.4,3,1.3,0.2,setosa
5.1,3.4,1.5,0.2,setosa
5,3.5,1.3,0.3,setosa
4.5,2.3,1.3,0.3,setosa
4.

In [66]:
# Carregando um dataset para dentro de um array
arquivo = np.loadtxt(filename, delimiter=',', usecols=(0, 1, 2, 3), skiprows=1)
print(arquivo)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [67]:
type(arquivo)

numpy.ndarray

In [ ]:
# Gerando um plot a partir de um arquivo usando o NumPy
var1, var2 = np.loadtxt(filename, delimiter=',', usecols=(0, 1), skiprows=1, unpack=True)
plt.show(plt.plot(var1, var2, 'o', markersise=8, alpha=0.75))

## Estatística

In [68]:
# Criando um array
A = np.array([15, 23, 63, 94, 75])

In [69]:
# Em estatística a média é o valor que aponta para onde mais se concentram os dados de uma distribuição.
np.mean(A)

54.0

In [70]:
# O desvio padrão mostra o quanto de variação ou "dispersão" existe em relação à média (ou valor esperado).
# Um baixo desvio padrão indica que os dados tendem a estar próximos da média.
# Um desvio padrão alto indica que os dados estão espalhados por uma gama de valores.
np.std(A)

30.34468652004828

In [71]:
# Variância de uma variável aleatória é uma medida da sua dispersão estatística, indicando "o quão longe" em geral os seus
# Valores se encontram do valor esperado
np.var(A)

920.8

In [72]:
d = np.arange(1, 10)

In [73]:
d

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
np.sum(d)

45

In [75]:
# Retorna o produto dos elementos
np.prod(d)

362880

In [76]:
# Soma acumulada dos elementos
np.cumsum(d)

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45])

In [77]:
a = np.random.randn(400, 2)
m = a.mean(0)
print(m, m.shape)

[ 0.02780248 -0.02266661] (2,)


In [ ]:
plt.plot(a[:, 0], a[:, 1], 'o', markersize=5, alpha=0.50)
plt.plot(m[0], m[1], 'ro', markersize=10)
plt.show()

## Outras Operações com Arrays

In [78]:
# Slicing
a = np.diag(np.arange(3))

In [79]:
a

array([[0, 0, 0],
       [0, 1, 0],
       [0, 0, 2]])

In [80]:
a[1, 1]

1

In [81]:
a[1]

array([0, 1, 0])

In [82]:
b = np.arange(10)

In [83]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [84]:
# [start:end:step]
b[2:9:3]

array([2, 5, 8])

In [85]:
# Comparação
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
a == b

array([False,  True, False,  True])

In [86]:
np.array_equal(a, b)

False

In [87]:
a.min()

1

In [88]:
a.max()

4

In [89]:
# Somando um elemento ao array
np.array([1, 2, 3]) + 1.5

array([2.5, 3.5, 4.5])

In [90]:
# Usando o método around
a = np.array([1.2, 1.5, 1.6, 2.5, 3.5, 4.5])

In [91]:
b = np.around(a)

In [92]:
b

array([1., 2., 2., 2., 4., 4.])

In [93]:
# Criando um array
B = np.array([1, 2, 3, 4])

In [94]:
B

array([1, 2, 3, 4])

In [95]:
# Copiando um array
C = B.flatten()

In [96]:
C

array([1, 2, 3, 4])

In [97]:
# Criando um array
v = np.array([1, 2, 3])

In [98]:
# Adicionando uma dimensão ao array
v[:, np.newaxis], v[:, np.newaxis].shape, v[np.newaxis, :].shape

(array([[1],
        [2],
        [3]]),
 (3, 1),
 (1, 3))

In [99]:
# Repetindo os elementos de um array
np.repeat(v, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [100]:
# Repetindo os elementos de um array
np.tile(v, 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [101]:
# Criando um array
w = np.array([5, 6])

In [102]:
# Concatenando
np.concatenate((v, w), axis=0)

array([1, 2, 3, 5, 6])

In [103]:
# Copiando arrays
r = np.copy(v)

In [104]:
r

array([1, 2, 3])

## Fim